config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "closets#index"
  resources :users, only: [:edit, :update]
  resources :closets, only: [:index, :new, :create, :show, :destroy] do
    resources :memos, only: [:create, :destroy]
    resource :favorites, only: [:create]
    collection do
      get 'stats'
    end
  end
  resources :calendars, only: [:index, :new, :create, :destroy]
end

app/models/closet.rb
class Closet < ApplicationRecord
  belongs_to :user
  has_many :memos, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :color
  belongs_to :season
  belongs_to :size

  validates :image,     presence: true
  validates :brand,     presence: true, length: { maximum: 40 }
  validates :genre_id,  presence: true, numericality: { other_than: 0, message: "can't be blank" }
  validates :color_id,  presence: true, numericality: { other_than: 0, message: "can't be blank" }
  validates :season_id, presence: true, numericality: { other_than: 0, message: "can't be blank" }
  validates :size_id,   presence: true, numericality: { other_than: 0, message: "can't be blank" }
  with_options presence: true, format: { with: /\A[0-9]+\z/, message: 'is invalid. Input half-width characters' } do
    validates :price,
              numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 9_999_999,
                              message: 'out of setting range' }
  end
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController
  before_action :closet_find, only: [:show, :destroy]

  def index
    @closets = Closet.where(user_id: current_user.id).order(:color_id)
    @memos = Memo.all
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
    @memo = Memo.new
  end

  def new
    @closet = Closet.new
  end

  def create
    @closet = Closet.new(closet_params)
    if @closet.save
      redirect_to root_path
    else
      flash.now[:alert] = '項目を入力してください'
      render :new
    end
  end

  def destroy
    @closet.destroy
    redirect_to root_path
  end

  def stats
    @closets = Closet.where(user_id: current_user.id)
    @closets_month = Closet.group('MONTH(created_at)').where(user_id: current_user.id)
    @favorite_desc_spring = Closet.includes(:favorites).where(season_id: 1, user_id: current_user.id).sort do |a, b|
      b.favorites.size <=> a.favorites.size
    end.first(10)
    @favorite_asc_spring = Closet.includes(:favorites).where(season_id: 1, user_id: current_user.id).sort do |a, b|
      a.favorites.size <=> b.favorites.size
    end.first(10)
    @favorite_desc_summer = Closet.includes(:favorites).where(season_id: 2, user_id: current_user.id).sort do |a, b|
      b.favorites.size <=> a.favorites.size
    end.first(10)
    @favorite_asc_summer = Closet.includes(:favorites).where(season_id: 2, user_id: current_user.id).sort do |a, b|
      a.favorites.size <=> b.favorites.size
    end.first(10)
    @favorite_desc_autumn = Closet.includes(:favorites).where(season_id: 3, user_id: current_user.id).sort do |a, b|
      b.favorites.size <=> a.favorites.size
    end.first(10)
    @favorite_asc_autumn = Closet.includes(:favorites).where(season_id: 3, user_id: current_user.id).sort do |a, b|
      a.favorites.size <=> b.favorites.size
    end.first(10)
    @favorite_desc_winter = Closet.includes(:favorites).where(season_id: 4, user_id: current_user.id).sort do |a, b|
      b.favorites.size <=> a.favorites.size
    end.first(10)
    @favorite_asc_winter = Closet.includes(:favorites).where(season_id: 4, user_id: current_user.id).sort do |a, b|
      a.favorites.size <=> b.favorites.size
    end.first(10)
  end

  private

  def closet_params
    params.require(:closet).permit(:brand, :price, :image, :genre_id, :color_id, :season_id,
                                   :size_id).merge(user_id: current_user.id)
  end

  def closet_find
    @closet = Closet.find(params[:id])
  end
end

app/helpers/closets_helper.rb
module ClosetsHelper
end

app/views/closets/_closet_show.html.erb
<div class="show">

  <div class="show-menu">
    <div class="delete-img"><%= link_to image_tag("delete.png"), closet_path(@closet.id), method: :delete, data: { confirm: "削除しますか？" } %></div>
  </div>

  <div class="show-contents">

    <div class="show-left">
      <div class="show-image"><%= image_tag @closet.image %></div>
      <div class="show-category scroll"><%= "ブランド：#{@closet.brand}" %></div>
      <div class="show-category"><%= "サイズ：#{@closet.size.name}" %></div>
      <div class="show-category"><%= "カラー：#{@closet.color.name}" %></div>
      <div class="show-category"><%= "購入金額：#{@closet.price}" %></div>
      <div class="show-category"><%= "保管日：#{@closet.created_at.strftime('%Y/%m/%d')}" %></div>
      <div id="favorite_area_<%= @closet.id %>", class="favoriteArea">
        <%= render partial: "favorites/favorite", locals: { closet: @closet } %>
      </div>
    </div>

    <div class="show-right">

      <div id="memo-display">
        <%= render 'memos/post_memos', closet: @closet %>
      </div>

      <div class="memo-form">
        <%= render 'memos/form', closet: @closet, memo: @memo %>
      </div>
      <div class="space"></div>

    </div>

  </div>

</div>

app/views/closets/calendar.html.erb
<div class="calender-contents">

  <div class="calendar-title">コーディネート</div>
  <%= week_calendar(number_of_weeks: 1) do |date| %>
    <div class="date-area">
    <%= date %>
    
    </div>
  <% end %>

</div>

app/views/closets/index.html.erb
<div class="closet-contents">

  <div class="closet-header">
    <div class="closet-header-title">CLOSET</div>
  </div>

  <div class="tab-panel">
    <!--タブ-->
    <ul class="tab-group">
      <li class="tab tab-A is-active spring">春</li>
      <li class="tab tab-B summer" >夏</li>
      <li class="tab tab-C autumn">秋</li>
      <li class="tab tab-D winter">冬</li>
      <li class="tab tab-F others">他</li>
    </ul>
    
    <!--タブを切り替えて表示するコンテンツ-->
    <div class="panel-group">

      <div class="panel tab-A is-show">

        <div class="tab-contents">
          
          <div class="tab-lists">
            <ul class="tab-list">
              <li class="tab-passive tab-active">アウター</li>
              <li class="tab-passive">/ トップス</li>
              <li class="tab-passive">/ ボトムス</li>  
            </ul>
          </div>
          
          <div class="tab-content">
            <div class="tab-box box-show">
              <div class="genre-images">
                <% @closets.where(genre_id: 1, season_id: 1).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 2, season_id: 1).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 3, season_id: 1).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>

      </div>

      <div class="panel tab-B">
        
        <div class="tab-contents">
          
          <div class="tab-lists">
            <ul class="tab-list">
              <li class="tab-passive tab-active">アウター</li>
              <li class="tab-passive">/ トップス</li>
              <li class="tab-passive">/ ボトムス</li>  
            </ul>
          </div>
          
          <div class="tab-content">
            <div class="tab-box box-show">
              <div class="genre-images">
                <% @closets.where(genre_id: 1, season_id: 2).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 2, season_id: 2).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 3, season_id: 2).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>

      </div>

      <div class="panel tab-C">
        
        <div class="tab-contents">
          
          <div class="tab-lists">
            <ul class="tab-list">
              <li class="tab-passive tab-active">アウター</li>
              <li class="tab-passive">/ トップス</li>
              <li class="tab-passive">/ ボトムス</li>  
            </ul>
          </div>
          
          <div class="tab-content">
            <div class="tab-box box-show">
              <div class="genre-images">
                <% @closets.where(genre_id: 1, season_id: 3).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 2, season_id: 3).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 3, season_id: 3).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>

      </div>

      <div class="panel tab-D">

        <div class="tab-contents">
          
          <div class="tab-lists">
            <ul class="tab-list">
              <li class="tab-passive tab-active">アウター</li>
              <li class="tab-passive">/ トップス</li>
              <li class="tab-passive">/ ボトムス</li>  
            </ul>
          </div>
          
          <div class="tab-content">
            <div class="tab-box box-show">
              <div class="genre-images">
                <% @closets.where(genre_id: 1, season_id: 4).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 2, season_id: 4).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 3, season_id: 4).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>

      </div>

      <div class="panel tab-F">
        
        <div class="tab-contents">
          
          <div class="tab-lists">
            <ul class="tab-list">
              <li class="tab-passive tab-active">キャップ</li>
              <li class="tab-passive">/ シューズ</li>
              <li class="tab-passive">/ バッグ</li>  
            </ul>
          </div>
          
          <div class="tab-content">
            <div class="tab-box box-show">
              <div class="genre-images">
                <% @closets.where(genre_id: 4, season_id: 5).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 5, season_id: 5).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="tab-box">
              <div class="genre-images">
                <% @closets.where(genre_id: 6, season_id: 5).each do |closet| %>
                  <div class="genre-image">
                    <%= link_to closet_path(closet.id), remote: true do %>
                      <%= image_tag closet.image %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>

      </div>

    </div>
  </div>

  <div class="page-footer"></div>
  
</div>

<div id="mask" class="hidden"><span id="closeBtn"></span></div>
<div id="modal" class="hidden">
  <p>モーダルウィンドウ<p>
</div>

app/views/closets/new.html.erb
<div class="clothes-form-content">
  <div class="notifications">
    <div class="alert"><%= alert %></div>
  </div>
    <%= form_with(model: @closet, id: 'post-form', local: true) do |form| %>
      <div class="clothes-form">

        <div class="image-preview">
          <div id="previews"></div>
          <div id="preview-none"><%= image_tag "noimage.png" %></div>
          <div class="image-form"><%= form.file_field :image %></div>
        </div>

        <div class="form-right" >
        <div class="clothes-category"><%= form.text_field :brand, placeholder: "ブランド" %></div>
        <div class="clothes-category"><%= form.text_field :price, placeholder:"購入額" %></div>
        <div class="clothes-category"><%= form.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre"}) %></div>
        <div class="clothes-category"><%= form.collection_select(:color_id, Color.all, :id, :name, {}, {class:"select-box", id:"clothes-category"}) %></div>
        <div class="clothes-category"><%= form.collection_select(:size_id, Size.all, :id, :name, {}, {class:"select-box", id:"size"}) %></div>
        <div class="clothes-category"><%= form.collection_select(:season_id, Season.all, :id, :name, {}, {class:"select-box", id:"season"}) %></div>
        <div class="closet-submit"><%= form.submit "保管する" %></div>
        </div>

      </div>
    <% end %>
</div>

app/views/closets/show.html.erb
<%= render partial: 'closets/closet_show', locals { closet: @closet, memo: @memo } %>

app/views/closets/show.js.erb
var modal = document.getElementById('modal');
var mask = document.getElementById('mask');

modal.innerHTML = '<%= escape_javascript(render partial: 'closets/closet_show', locals: { closet: @closets, memo: @memos }) %>';

modal.classList.remove('hidden');
mask.classList.remove('hidden');

mask.addEventListener('click', () => {
  modal.classList.add('hidden');
  mask.classList.add('hidden');
  });

app/views/closets/stats.html.erb
<div class="stats-title">統計</div>
<div class="stats-contents">
  <div>
    <div class="tab-panel panel-width">   

      <ul class="tab-group">
        <li class="tab tab-A is-active spring">春</li>
        <li class="tab tab-B summer" >夏</li>
        <li class="tab tab-C autumn">秋</li>
        <li class="tab tab-D winter">冬</li>
      </ul>

      <div class="panel-group panel-height">
        <div class="panel tab-A is-show">
          <div class="panel-category">カテゴリー</div>    
          <div class="canvas-area">
            <div class="canvas"><%= pie_chart @closets.where(season_id: 1).group(:genre_id).count, legend: false, colors: [ "#cd7693","#eab9c9","#f2d6df"]%></div>
            <div class="canvas-content">
              <div class="item-count">アイテム数</div>
              <% if @closets.where(season_id: 1, genre_id: 1).present? %>
                <div class="category-count"><span class="spring1">●</span><%= "アウター：#{@closets.where(genre_id: 1, season_id: 1).length}" %></div>
              <% end %>
              <% if @closets.where(season_id: 1, genre_id: 2).present? %>
                <div class="category-count">
                <% if @closets.where(season_id: 1, genre_id: 1).blank? %>
                <span class="spring1">●</span>
                <% else %>
                <span class="spring2">●</span>
                <% end %>
                <%= "トップス：#{@closets.where(genre_id: 2, season_id: 1).length}" %>
                </div>
              <% end %>
              <% if @closets.where(season_id: 1, genre_id: 3).present? %>
                <div class="category-count">
                  <% if @closets.where(season_id: 1, genre_id: 1).blank? && @closets.where(season_id: 1, genre_id: 2).blank? %>
                  <span class="spring1">●</span>
                  <% elsif @closets.where(season_id: 1, genre_id: 1).blank? || @closets.where(season_id: 1, genre_id: 2).blank? %>
                  <span class="spring2">●</span>
                  <% else %>
                  <span class="spring3">●</span>
                  <% end %>
                  <%= "ボトムス：#{@closets.where(genre_id: 3, season_id: 1).length}" %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="under">
            <% if @favorite_desc_spring.present? %>
              <div class="favorite-title desc">着用回数が多いアイテム</div>
              <div class="stats-images">
                <% @favorite_desc_spring.each do |closet| %>
                  <div>
                  <div class="stats-image"><%= image_tag closet.image %></div>
                  <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                  </div>
                <% end %>
              </div>
              <div class="favorite-title">着用回数が少ないアイテム</div>
              <div class="stats-images">
                <% @favorite_asc_spring.each do |closet| %>
                  <div>
                  <div class="stats-image"><%= image_tag closet.image %></div>
                  <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="panel tab-B">

          <div class="canvas-area">
            <div class="panel-category">カテゴリー</div>
            <div class="canvas"><%= pie_chart @closets.where(season_id: 2).group(:genre_id).count, legend: false, colors: [ "#76cd76","#b9eaba","#d6f2d6"] %></div>
            <div class="canvas-content">
              <div class="item-count">アイテム数</div>
              <% if @closets.where(season_id: 2, genre_id: 1).present? %>
                <div class="category-count"><span class="summer1">●</span><%= "アウター：#{@closets.where(genre_id: 1, season_id: 2).length}" %></div>
              <% end %>
              <% if @closets.where(season_id: 2, genre_id: 2).present? %>
                <div class="category-count">
                <% if @closets.where(season_id: 2, genre_id: 1).blank? %>
                <span class="summer1">●</span>
                <% else %>
                <span class="summer2">●</span>
                <% end %>
                <%= "トップス：#{@closets.where(genre_id: 2, season_id: 2).length}" %>
                </div>
              <% end %>
              <% if @closets.where(season_id: 2, genre_id: 3).present? %>
                <div class="category-count">
                  <% if @closets.where(season_id: 2, genre_id: 1).blank? && @closets.where(season_id: 2, genre_id: 2).blank? %>
                  <span class="summer1">●</span>
                  <% elsif @closets.where(season_id: 2, genre_id: 1).blank? || @closets.where(season_id: 2, genre_id: 2).blank? %>
                  <span class="summer2">●</span>
                  <% else %>
                  <span class="summer3">●</span>
                  <% end %>
                  <%= "ボトムス：#{@closets.where(genre_id: 3, season_id: 2).length}" %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="under">
            <% if @favorite_desc_summer.present? %>
              <div class="favorite-title desc">着用回数が多いアイテム</div>
              <div class="stats-images">
              <% @favorite_desc_summer.each do |closet| %>
                <div>
                <div class="stats-image"><%= image_tag closet.image %></div>
                <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                </div>
              <% end %>
              </div>
              <div class="favorite-title">着用回数が少ないアイテム</div>
              <div class="stats-images">
              <% @favorite_asc_summer.each do |closet| %>
                <div>
                <div class="stats-image"><%= image_tag closet.image %></div>
                <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                </div>
              <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="panel tab-C">

          <div class="canvas-area">
            <div class="panel-category">カテゴリー</div>
            <div class="canvas"><%= pie_chart @closets.where(season_id: 3).group(:genre_id).count, legend: false, colors: [ "#cd9376","#eac9b9","#f2dfd6"] %></div>
            <div class="canvas-content">
              <div class="item-count">アイテム数</div>
              <% if @closets.where(season_id: 3, genre_id: 1).present? %>
                <div class="category-count"><span class="autumn1">●</span><%= "アウター：#{@closets.where(genre_id: 1, season_id: 3).length}" %></div>
              <% end %>
              <% if @closets.where(season_id: 3, genre_id: 2).present? %>
                <div class="category-count">
                <% if @closets.where(season_id: 3, genre_id: 1).blank? %>
                <span class="autumn1">●</span>
                <% else %>
                <span class="autumn2">●</span>
                <% end %>
                <%= "トップス：#{@closets.where(genre_id: 2, season_id: 3).length}" %>
                </div>
              <% end %>
              <% if @closets.where(season_id: 3, genre_id: 3).present? %>
                <div class="category-count">
                  <% if @closets.where(season_id: 3, genre_id: 1).blank? && @closets.where(season_id: 3, genre_id: 2).blank? %>
                  <span class="autumn1">●</span>
                  <% elsif @closets.where(season_id: 3, genre_id: 1).blank? || @closets.where(season_id: 3, genre_id: 2).blank? %>
                  <span class="autumn2">●</span>
                  <% else %>
                  <span class="autumn3">●</span>
                  <% end %>
                  <%= "ボトムス：#{@closets.where(genre_id: 3, season_id: 3).length}" %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="under">
            <% if @favorite_desc_autumn.present? %>
              <div class="favorite-title desc">着用回数が多いアイテム</div>
              <div class="stats-images">
                <% @favorite_desc_autumn.each do |closet| %>
                  <div>
                  <div class="stats-image"><%= image_tag closet.image %></div>
                  <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                  </div>
                <% end %>
              </div>
              <div class="favorite-title">着用回数が少ないアイテム</div>
              <div class="stats-images">
                <% @favorite_asc_autumn.each do |closet| %>
                  <div>
                  <div class="stats-image"><%= image_tag closet.image %></div>
                  <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="panel tab-D">

          <div class="canvas-area">
            <div class="panel-category">カテゴリー</div>
            <div class="canvas"><%= pie_chart @closets.where(season_id: 4).group(:genre_id).count, legend: false, colors: [ "#769fcd","#b9d7ea","#d6e6f2"]%></div>
            <div class="canvas-content">
              <div class="item-count">アイテム数</div>
              <% if @closets.where(season_id: 4, genre_id: 1).present? %>
                <div class="category-count"><span class="winter1">●</span><%= "アウター：#{@closets.where(genre_id: 1, season_id: 4).length}" %></div>
              <% end %>
              <% if @closets.where(season_id: 4, genre_id: 2).present? %>
                <div class="category-count">
                <% if @closets.where(season_id: 4, genre_id: 1).blank? %>
                <span class="winter1">●</span>
                <% else %>
                <span class="winter2">●</span>
                <% end %>
                <%= "トップス：#{@closets.where(genre_id: 2, season_id: 4).length}" %>
                </div>
              <% end %>
              <% if @closets.where(season_id: 4, genre_id: 3).present? %>
                <div class="category-count">
                  <% if @closets.where(season_id: 4, genre_id: 1).blank? && @closets.where(season_id: 4, genre_id: 2).blank? %>
                  <span class="winter1">●</span>
                  <% elsif @closets.where(season_id: 4, genre_id: 1).blank? || @closets.where(season_id: 4, genre_id: 2).blank? %>
                  <span class="winter2">●</span>
                  <% else %>
                  <span class="winter3">●</span>
                  <% end %>
                  <%= "ボトムス：#{@closets.where(genre_id: 3, season_id: 4).length}" %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="under">
            <% if @favorite_desc_winter.present? %>
              <div class="favorite-title desc">着用回数が多いアイテム</div>
              <div class="stats-images">
                <% @favorite_desc_winter.each do |closet| %>
                  <div>
                  <div class="stats-image"><%= image_tag closet.image %></div>
                  <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                  </div>
                <% end %>
              </div>
              <div class="favorite-title">着用回数が少ないアイテム</div>
              <div class="stats-images">
                <% @favorite_asc_winter.each do |closet| %>
                  <div>
                  <div class="stats-image"><%= image_tag closet.image %></div>
                  <div class="stats-count"><%= "#{closet.favorites.count}回" %></div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>

        </div>

      </div>
    </div>

  </div>

  <div class="stats-right">
    <div class="date">クローゼット総資産額：<span><%= "¥#{@closets.sum(:price)}" %></span></div>
    <div class="date">アイテム平均価格：
      <% if @closets.present? %>
        <span><%= "¥#{@closets.sum(:price).fdiv(@closets.length).round}"%></span>
      <% else %>
        <span>¥0</span>
      <% end %>
    </div>
    <div class="date">アイテム最高価格：
      <% if @closets.present? %>
        <span><%= "¥#{@closets.maximum(:price)}"%></span>
      <% else %>
        <span>¥0</span>
      <% end %>
    </div>
    <div class="date bottom">所持アイテム数：<span><%= "#{@closets.length}"%></span></div>
    <div class="date">今月の使用額：
      <% if @closets_month.present? %>
        <span><%= "¥#{@closets_month.sum(:price)[Date.today.month]}"%></span>
      <% else %>
        <span>¥0</span>
      <% end %>
    </div>
    <div class="date">今月のアイテム最高価格：
      <% if @closets_month.present? %>
        <span><%= "¥#{@closets_month.maximum(:price)[Date.today.month]}" %></span>
      <% else %>
        <span>¥0</span>
      <% end %>
    </div>
    <div class="date">今月の保管アイテム数：
      <% if @closets_month.present? %>
        <span><%= "#{@closets_month.count[Date.today.month]}"%></span>
      <% else %>
        <span>0</span>
      <% end %>
    </div>
  </div>

</div>
<div class="page-footer"></div>