config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "closets#index"
  resources :users, only: [:edit, :update]
  resources :closets, only: [:index, :new, :create, :show, :destroy] do
    resources :memos, only: [:create, :destroy]
    resource :favorites, only: [:create]
    collection do
      get 'stats'
    end
  end
  resources :calendars, only: [:index, :new, :create, :destroy]
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  validates :start_time, presence: true
  validates :images, presence: true
  validates :images, length: { minimum: 1, maximum: 6, message: 'は1枚以上6枚以下にしてください' }
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @calendars = Calendar.where(user_id: current_user.id).all
  end

  def new
    @calendar = Calendar.new
  end

  def create
    @calendar = Calendar.new(calendar_params)
    if @calendar.save
      redirect_to calendars_path
    else
      redirect_to calendars_path
    end
  end

  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    redirect_to calendars_path
  end

  private

  def calendar_params
    params.permit(:start_time, { images: [] }).merge(user_id: current_user.id)
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_new.html.erb
<div class="calendar-form">
  <%= form_with(model: @calendar, local: true) do |form| %>
    <div class="calendar-time"><%= form.date_select :start_time %></div>
    <div class="calendar-file"><%= form.file_field :images, multiple: true %></div>
    <div class="calendar-submit"><%= form.submit "追加する" %></div>
  <% end %>
</div>

app/views/calendars/_weather.html.erb
<div class="weather">
  <h3 class="weather__title">天気予報</h3>
  <div id="weather"></div>
</div>
<script type="text/javascript">
$(function () {

  // 緯度経度を取得
  const latlon_url = 'https://api.openweathermap.org/geo/1.0/direct?q=<%= current_user.prefecture_name %>&appid=<%= ENV['OPEN_WEATHER_MAP_API']%>';

  $.ajax({
    url: latlon_url,
    dataType: "json",
    type: 'GET',
  })
  .done(function (latlon) {
    const lat = latlon[0].lat
    const lon = latlon[0].lon

    // 天気予報を取得
    const weather_url = 'https://api.openweathermap.org/data/3.0/onecall?lat=' + lat + '&lon=' + lon + '&exclude=current,minutely,hourly,alerts&units=metric&appid=<%= ENV['OPEN_WEATHER_MAP_API'] %>';

    $.ajax({
        url: weather_url,
        dataType: 'json',
        type: 'GET',
      })
      .done(function (weather) {
        let insertHTML = '';

        for (let i = 0; i <= 6; i = i + 1) {
          insertHTML += buildHTML(weather, i);
        }
        $('#weather').html(insertHTML);
      })
      .fail(function (weather) {
        alert('天気予報の取得に失敗しました');
      });
  })
});

// 日本語で表示
function buildHTML(weather, i) {
  //日付、時間を取得（Dateがミリ秒なので1000倍が必要）
  const date = new Date(weather.daily[i].dt * 1000);
  //UTCとの時差を無くす(日本は-9時間のため9を足す)
  date.setHours(date.getHours() + 9);
  //月を取得。getMonth()は0~11を返すため1を足すことによって1月~12月を返すように設定
  const month = date.getMonth() + 1;
  //曜日の日本語化のため、配列を用意する
  const Week = new Array('(日)', '(月)', '(火)', '(水)', '(木)', '(金)', '(土)');
  //月＋日＋曜日をdayに代入。getDay()は0~6を返すためWeek配列内のインデックスに対応した文字列を取得
  const day = month + '/' + date.getDate() + Week[date.getDay()];
  //天気のアイコンを取得
  const icon = weather.daily[i].weather[0].icon;

  const html =
    '<div class="weather__content--report">' +
      '<img src="https://openweathermap.org/img/w/' + icon + '.png">' +
      '<span class="weather__content--report-date">' + day + "</span>" +
      '<div class="weather__content--report-temp-max">' + '最高：' + Math.round(weather.daily[i].temp.max) + "℃</div>" +
      '<span class="weather__content--report-temp-min">' + '最低：' + Math.floor(weather.daily[i].temp.min) + "℃</span>" +
    '</div>';
  return html
}
</script>

app/views/calendars/index.html.erb
<div class="calendar-contents">

  <div class="calendar-title">コーディネート</div>

  <%= render "weather" %>

  <div class="calendar-new">
  <%= render partial: "new", locals: { calendar: @calendar }%>
  </div>

  <div class="calender-week">
    <%= week_calendar events: @calendars do |date, calendars| %>
      <div class="date-area">
        <div class="calendar-date"><%= "#{date.month}/#{date.day}" %></div>

        <% calendars.each do |calendar| %>
        <%= link_to calendar_path(calendar.id), method: :delete, data: { confirm: "削除しますか？" } do %>
          <%= image_tag calendar.images[0], class: "main-image" %>
        <% end %>
        <div class="other-images">
          <% calendar.images[1..-1].each do |image| %>
            <div class="other-image">
              <%= image_tag image %>
            </div>
          <%end%>
        </div>
        <% end %>
          
      </div>
    <% end %>
  </div>

  <div class="page-footer"></div>

</div>

app/views/calendars/new.html.erb
<%= render partial: "new", locals: { calendar: @calendar }%>