config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "closets#index"
  resources :users, only: [:edit, :update]
  resources :closets, only: [:index, :new, :create, :show, :destroy] do
    resources :memos, only: [:create, :destroy]
    resource :favorites, only: [:create]
    collection do
      get 'stats'
    end
  end
  resources :calendars, only: [:index, :new, :create, :destroy]
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :closet

  validates :content, presence: true
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    @closet = Closet.find(params[:closet_id])
    @memo = current_user.memos.new(memo_params)
    render :post_memos if @memo.save
  end

  def destroy
    Memo.find_by(id: params[:id], closet_id: params[:closet_id]).destroy
    @closet = Closet.find(params[:closet_id])
    render :post_memos
  end

  private

  def memo_params
    params.require(:memo).permit(:content).merge(user_id: current_user.id, closet_id: params[:closet_id])
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= form_with model: [@closet, @memo], id: "memo-form" do |f| %>
  <div class="memo-form-display">
    <%= f.text_field :content, class: "memo-content", placeholder: "メモ" %>
    <%= f.submit "作成", class: "memo-form-submit" %>
  </div>
<% end %>

app/views/memos/_post_memos.html.erb
<% @closet.memos.each do |memo| %>
  <div class="memo">
    <p>
    <%= link_to "#{memo.content}",closet_memo_path(closet.id, memo), method: :delete, remote: true, data: { confirm: "削除しますか？" } %>
    </p>
  </div>
<% end %>

app/views/memos/post_memos.js.erb
$("#memo-display").html("<%= j(render 'memos/post_memos', closet: @closet, memo: @memo) %>");
$(".memo-content").val('');